import type { Terms } from "./fr";

export const en = {
  Common: {
    loading: "Loading",
    error: "Error",
    back: "Back",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    email: "Email",
    password: "Password",
    darkMode: "Dark mode",
    logout: "Log out",
    admin: "Admin",
    user: "User",
    you: "You",
    enterprise: "Enterprise",
    individual: "Individual",
    learnMore: "Learn more",
    language: "Language",
    french: "Français",
    english: "English",
  },

  Header: {
    dashboard: "Dashboard",
    newProject: "New project",
    users: "Users",
  },

  Login: {
    title: "Login",
    description: "Sign in to access your audit projects",
    emailLabel: "Email",
    emailPlaceholder: "you@example.com",
    passwordLabel: "Password",
    passwordPlaceholder: "••••••••",
    submit: "Sign in",
    submitting: "Signing in...",
    noAccount: "Don't have an account?",
    createAccount: "Create an account",
    validationRequired: "Email and password are required",
    toastWelcome: (name: string) => `Welcome ${name}!`,
    toastError: "Error during login",
  },

  Register: {
    title: "Create an account",
    description: "Sign up to start your accessibility audits",
    firstNameLabel: "First name",
    firstNamePlaceholder: "John",
    lastNameLabel: "Last name",
    lastNamePlaceholder: "Doe",
    emailLabel: "Email",
    emailPlaceholder: "john.doe@example.com",
    organisationLabel: "Organisation",
    enterprise: "🏢 Enterprise",
    individual: "👤 Individual",
    passwordLabel: "Password",
    passwordPlaceholder: "••••••••",
    passwordMinChars: "Minimum 6 characters",
    confirmPasswordLabel: "Confirm password",
    confirmPasswordPlaceholder: "••••••••",
    submit: "Create my account",
    submitting: "Creating account...",
    alreadyHaveAccount: "Already have an account?",
    login: "Sign in",
    validationAllFieldsRequired: "All fields are required",
    validationPasswordMinLength: "Password must be at least 6 characters",
    validationPasswordsMismatch: "Passwords do not match",
    toastWelcome: (name: string) => `Welcome ${name}! Your account has been created.`,
    toastError: "Error creating account",
  },

  Dashboard: {
    title: "Dashboard",
    subtitle: "Manage your RGAA accessibility projects and audits",
    newProject: "New project",
    noProjects: "No projects",
    noProjectsDescription: "Create your first project to launch an RGAA audit",
    createProject: "Create a project",
    errorLoading: (msg: string) => `Error loading projects: ${msg}`,
  },

  ProjectCard: {
    createdOn: "Created on",
    delete: "Delete",
    viewProject: "View project",
    confirmDelete: "Delete this project and all its audits?",
    toastDeleted: "Project deleted",
  },

  ProjectDetail: {
    notFound: "Project not found",
    backToDashboard: "Back to dashboard",
    back: "Back",
    backToAudits: "Back to audits",
    authConfigured: "Authentication configured",
    additionalPages: (count: number) => `${count} additional page(s) configured`,
    startAudit: "Start an audit",
    auditRunning: "Audit running...",
    launching: "Launching...",
    authRequired: "Authentication required",
    authRequiredDescription: "A browser has opened. Sign in on the website, then click the button below to continue the audit.",
    authConfirmButton: "I have finished logging in",
    confirming: "Confirming...",
    authConfirmed: "Authentication confirmed! The audit continues...",
    authConfirmError: "Error during confirmation",
    auditInProgress: "Audit in progress...",
    auditInProgressDescription: "Discovering pages and analyzing accessibility. This may take a few minutes.",
    previousAudits: "Previous audits",
    compliance: "Compliance",
    pagesAudited: (count: number) => `${count} page(s) audited`,
    auditNotFound: "Audit not found",
    auditCompleted: "Audit completed!",
    auditError: (msg: string) => `Error: ${msg}`,
    auditStarted: "Audit started! This may take a moment...",
    auditStartError: "Error starting audit",
    permissions: "Permissions",
    permissionsDescription: "Manage users with access to this project",
    noOtherUsers: "No other registered users",
    remove: "Remove",
    authorize: "Authorize",
    accessRemoved: (name: string) => `Access removed for ${name}`,
    accessGranted: (name: string) => `Access granted to ${name}`,
    statusCompleted: "Completed",
    statusRunning: "Running",
    statusWaitingAuth: "Authentication",
    statusPending: "Pending",
    statusError: "Error",
  },

  ProjectForm: {
    title: "New project",
    description: "Create a project to launch an RGAA accessibility audit",
    projectNameLabel: "Project name",
    projectNamePlaceholder: "My website",
    descriptionLabel: "Description",
    descriptionPlaceholder: "Description of the website to audit...",
    urlLabel: "Main URL",
    urlPlaceholder: "https://example.com",
    urlDescription: "The homepage URL of the site (after login if authentication is enabled)",
    additionalPagesLabel: "Pages to audit (optional)",
    additionalPagesDescription: "The tool will automatically discover internal links, but you can also add specific URLs to audit.",
    additionalPagesPlaceholder: "/my-page or https://example.com/page",
    authRequired: "Authentication required",
    authDescription: "🔐 When starting the audit, a browser will open on the login page. Sign in manually, then confirm in the application to continue the audit.",
    loginUrlLabel: "Login page URL (optional)",
    loginUrlPlaceholder: "https://example.com/login",
    loginUrlDescription: "If empty, the main URL will be used",
    submit: "Create project",
    submitting: "Creating...",
    validationAllFieldsRequired: "All fields are required",
    validationInvalidUrl: "Invalid URL. Check the format (e.g. https://example.com)",
    toastSuccess: "Project created successfully!",
    toastError: "Error creating project",
  },

  UserManagement: {
    title: "User management",
    subtitle: "Manage user accounts and roles",
    totalUsers: "Total users",
    administrators: "Administrators",
    users: "Users",
    allUsers: "All users",
    accountsRegistered: (count: number) => `${count} account(s) registered`,
    removeAdmin: "Remove admin",
    makeAdmin: "Make admin",
    roleUpdated: (name: string, role: string) =>
      `${name} is now ${role === "admin" ? "an administrator" : "a user"}`,
    deleteConfirm: (name: string) =>
      `Delete ${name}'s account? This action is irreversible.`,
    userDeleted: "User deleted",
    registeredOn: "Registered on",
    error: (msg: string) => `Error: ${msg}`,
  },

  AuditReport: {
    title: "RGAA Audit Report",
    auditDate: "Audit performed on",
    downloadPdf: "Download PDF",
    rgaaCriteria: "RGAA Criteria",
    violationsDetected: (count: number) => `Violations detected (${count})`,
    noViolations: "No violations detected 🎉",
    page: "Page",
    learnMore: "Learn more",
  },

  AuditSummary: {
    complianceRate: "Compliance rate",
    criteriaCompliantOf: (compliant: number, total: number) =>
      `${compliant} compliant criteria out of ${total} applicable`,
    pagesAudited: "Pages audited",
    compliant: "Compliant",
    nonCompliant: "Non-compliant",
    nonApplicable: "Not applicable",
    notTested: "Not tested",
    pagesAuditedTitle: (count: number) => `Pages audited (${count})`,
    error: "Error",
    violations: (count: number) =>
      `${count} violation${count > 1 ? "s" : ""}`,
    ok: (count: number) => `${count} OK`,
  },

  CriteriaGroup: {
    compliant: (count: number) => `${count} compliant`,
    nonCompliant: (count: number) => `${count} non-compliant`,
    criteria: (count: number) => `${count} ${count > 1 ? "criteria" : "criterion"}`,
    conforme: "Compliant",
    nonConforme: "Non-compliant",
    nonApplicable: "N/A",
    notTested: "Not tested",
    andOthers: (count: number) => `... and ${count} other(s)`,
  },
} as const;