export const fr = {
  Common: {
    loading: "Chargement",
    error: "Erreur",
    back: "Retour",
    delete: "Supprimer",
    save: "Enregistrer",
    cancel: "Annuler",
    email: "Email",
    password: "Mot de passe",
    darkMode: "Mode sombre",
    logout: "Se déconnecter",
    admin: "Admin",
    user: "Utilisateur",
    you: "Vous",
    enterprise: "Entreprise",
    individual: "Particulier",
    learnMore: "En savoir plus",
    language: "Langue",
    french: "Français",
    english: "English",
  },

  Header: {
    dashboard: "Dashboard",
    newProject: "Nouveau projet",
    users: "Utilisateurs",
  },

  Login: {
    title: "Connexion",
    description: "Connectez-vous pour accéder à vos projets d'audit",
    emailLabel: "Email",
    emailPlaceholder: "vous@exemple.com",
    passwordLabel: "Mot de passe",
    passwordPlaceholder: "••••••••",
    submit: "Se connecter",
    submitting: "Connexion...",
    noAccount: "Pas encore de compte ?",
    createAccount: "Créer un compte",
    validationRequired: "Email et mot de passe requis",
    toastWelcome: (name: string) => `Bienvenue ${name} !`,
    toastError: "Erreur lors de la connexion",
  },

  Register: {
    title: "Créer un compte",
    description: "Inscrivez-vous pour commencer vos audits d'accessibilité",
    firstNameLabel: "Prénom",
    firstNamePlaceholder: "Votre prénom",
    lastNameLabel: "Nom",
    lastNamePlaceholder: "Votre nom",
    emailLabel: "Email",
    emailPlaceholder: "vous@exemple.com",
    organisationLabel: "Organisation",
    enterprise: "🏢 Entreprise",
    individual: "👤 Particulier",
    passwordLabel: "Mot de passe",
    passwordPlaceholder: "••••••••",
    passwordMinChars: "Minimum 6 caractères",
    confirmPasswordLabel: "Confirmer le mot de passe",
    confirmPasswordPlaceholder: "••••••••",
    submit: "Créer mon compte",
    submitting: "Création du compte...",
    alreadyHaveAccount: "Déjà un compte ?",
    login: "Se connecter",
    validationAllFieldsRequired: "Tous les champs sont requis",
    validationPasswordMinLength: "Le mot de passe doit contenir au moins 6 caractères",
    validationPasswordsMismatch: "Les mots de passe ne correspondent pas",
    toastWelcome: (name: string) => `Bienvenue ${name} ! Votre compte a été créé.`,
    toastError: "Erreur lors de la création du compte",
  },

  Dashboard: {
    title: "Dashboard",
    subtitle: "Gérez vos projets et audits d'accessibilité RGAA",
    newProject: "Nouveau projet",
    noProjects: "Aucun projet",
    noProjectsDescription: "Créez votre premier projet pour lancer un audit RGAA",
    createProject: "Créer un projet",
    errorLoading: (msg: string) => `Erreur lors du chargement des projets : ${msg}`,
  },

  ProjectCard: {
    createdOn: "Créé le",
    delete: "Supprimer",
    viewProject: "Voir le projet",
    confirmDelete: "Supprimer ce projet et tous ses audits ?",
    toastDeleted: "Projet supprimé",
  },

  ProjectDetail: {
    notFound: "Projet introuvable",
    backToDashboard: "Retour au dashboard",
    back: "Retour",
    backToAudits: "Retour aux audits",
    authConfigured: "Authentification configurée",
    additionalPages: (count: number) => `${count} page(s) additionnelle(s) configurée(s)`,
    startAudit: "Lancer un audit",
    auditRunning: "Audit en cours...",
    launching: "Lancement...",
    authRequired: "Authentification requise",
    authRequiredDescription: "Un navigateur s'est ouvert. Connectez-vous sur le site, puis cliquez sur le bouton ci-dessous pour continuer l'audit.",
    authConfirmButton: "J'ai terminé la connexion",
    confirming: "Confirmation...",
    authConfirmed: "Authentification confirmée ! L'audit continue...",
    authConfirmError: "Erreur lors de la confirmation",
    auditInProgress: "Audit en cours...",
    auditInProgressDescription: "Découverte des pages et analyse de l'accessibilité. Cela peut prendre quelques minutes.",
    previousAudits: "Audits précédents",
    compliance: "Conformité",
    pagesAudited: (count: number) => `${count} page(s) auditée(s)`,
    auditNotFound: "Audit introuvable",
    auditCompleted: "Audit terminé !",
    auditError: (msg: string) => `Erreur : ${msg}`,
    auditStarted: "Audit lancé ! Cela peut prendre quelques instants...",
    auditStartError: "Erreur lors du lancement de l'audit",
    permissions: "Habilitations",
    permissionsDescription: "Gérez les utilisateurs ayant accès à ce projet",
    noOtherUsers: "Aucun autre utilisateur enregistré",
    remove: "Retirer",
    authorize: "Habiliter",
    accessRemoved: (name: string) => `Accès retiré pour ${name}`,
    accessGranted: (name: string) => `Accès accordé à ${name}`,
    statusCompleted: "Terminé",
    statusRunning: "En cours",
    statusWaitingAuth: "Authentification",
    statusPending: "En attente",
    statusError: "Erreur",
  },

  ProjectForm: {
    title: "Nouveau projet",
    description: "Créez un projet pour lancer un audit d'accessibilité RGAA",
    projectNameLabel: "Nom du projet",
    projectNamePlaceholder: "Mon site web",
    descriptionLabel: "Description",
    descriptionPlaceholder: "Description du site à auditer...",
    urlLabel: "URL principale",
    urlPlaceholder: "https://example.com",
    urlDescription: "L'URL de la page d'accueil du site (après connexion si authentification activée)",
    additionalPagesLabel: "Pages à auditer (optionnel)",
    additionalPagesDescription: "L'outil découvrira automatiquement les liens internes, mais vous pouvez aussi ajouter des URLs spécifiques à auditer.",
    additionalPagesPlaceholder: "/ma-page ou https://example.com/page",
    authRequired: "Authentification requise",
    authDescription: "🔐 Au lancement de l'audit, un navigateur s'ouvrira sur la page de login. Connectez-vous manuellement, puis confirmez dans l'application pour continuer l'audit.",
    loginUrlLabel: "URL de la page de login (optionnel)",
    loginUrlPlaceholder: "https://example.com/login",
    loginUrlDescription: "Si vide, l'URL principale sera utilisée",
    submit: "Créer le projet",
    submitting: "Création en cours...",
    validationAllFieldsRequired: "Tous les champs sont requis",
    validationInvalidUrl: "URL invalide. Vérifiez le format (ex: https://example.com)",
    toastSuccess: "Projet créé avec succès !",
    toastError: "Erreur lors de la création du projet",
  },

  UserManagement: {
    title: "Gestion des utilisateurs",
    subtitle: "Gérez les comptes et les rôles des utilisateurs",
    totalUsers: "Total utilisateurs",
    administrators: "Administrateurs",
    users: "Utilisateurs",
    allUsers: "Tous les utilisateurs",
    accountsRegistered: (count: number) => `${count} compte(s) enregistré(s)`,
    removeAdmin: "Retirer admin",
    makeAdmin: "Rendre admin",
    roleUpdated: (name: string, role: string) =>
      `${name} est maintenant ${role === "admin" ? "administrateur" : "utilisateur"}`,
    deleteConfirm: (name: string) =>
      `Supprimer le compte de ${name} ? Cette action est irréversible.`,
    userDeleted: "Utilisateur supprimé",
    registeredOn: "Inscrit le",
    error: (msg: string) => `Erreur : ${msg}`,
  },

  AuditReport: {
    title: "Rapport d'audit RGAA",
    auditDate: "Audit réalisé le",
    downloadPdf: "Télécharger PDF",
    rgaaCriteria: "Critères RGAA",
    violationsDetected: (count: number) => `Violations détectées (${count})`,
    noViolations: "Aucune violation détectée 🎉",
    page: "Page",
    learnMore: "En savoir plus",
  },

  AuditSummary: {
    complianceRate: "Taux de conformité",
    criteriaCompliantOf: (compliant: number, total: number) =>
      `${compliant} critères conformes sur ${total} applicables`,
    pagesAudited: "Pages auditées",
    compliant: "Conformes",
    nonCompliant: "Non conformes",
    nonApplicable: "Non applicables",
    notTested: "Non testés",
    pagesAuditedTitle: (count: number) => `Pages auditées (${count})`,
    error: "Erreur",
    violations: (count: number) =>
      `${count} violation${count > 1 ? "s" : ""}`,
    ok: (count: number) => `${count} OK`,
  },

  CriteriaGroup: {
    compliant: (count: number) => `${count} conforme${count > 1 ? "s" : ""}`,
    nonCompliant: (count: number) => `${count} non conforme${count > 1 ? "s" : ""}`,
    criteria: (count: number) => `${count} critère${count > 1 ? "s" : ""}`,
    conforme: "Conforme",
    nonConforme: "Non conforme",
    nonApplicable: "N/A",
    notTested: "Non testé",
    andOthers: (count: number) => `... et ${count} autre(s)`,
  },
} as const;

// Widen literal string types so en.ts can satisfy the same shape
type DeepWiden<T> = {
  [K in keyof T]: T[K] extends (...args: infer A) => infer R
    ? (...args: A) => R extends string ? string : R
    : T[K] extends object
      ? DeepWiden<T[K]>
      : T[K] extends string
        ? string
        : T[K];
};

export type Terms = DeepWiden<typeof fr>;